### ISSUE TITLE
Dev tools

### ISSUE THREAD

**Issue by hellkite500** [hellkite500/bmi_pytorch#3]
Document usage of and possibly automate some dev tooling

- [black](https://black.readthedocs.io/en/stable/)
- [flake8](https://flake8.pycqa.org/en/latest/)
- [isort](https://pycqa.github.io/isort/)
- [pre-commit](https://pre-commit.com/)

**Comment by taddyb** [comment]
Do you use ruff? It's black + isort + flake8 and built in rust 🥇 

https://github.com/astral-sh/ruff
